# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    #- mvn clean prepare-package war:exploded
    - mvn test
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - mvn clean
    - mvn package
    #- mv target/ ./
artifacts:
  files:
    - target/**/*
    #- deploy/**/*